### PR TITLE
Add extension targets

### PR DESCRIPTION
**Pull request by adam-fowler**
The issue with SwiftPM complaining about files that are in the target `path` but not in the `sources` folders is not going away. I posted this bug on feedback assistant 3 or 4 years back and then in the SwiftPM repo last year https://github.com/swiftlang/swift-package-manager/issues/6440 and there doesn't seem to be any movement on it. In actual fact now it has got worse as it is being reporting for users of soto and not just those compiling soto. See #730 

This PR would get around this by add new extension targets `SotoS3Extension` `SotoSTSExtension` etc but it is a breaking change and would require a soto v8.

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]

**Comment by MahdiBM** [comment]
I'm curious to know what is the breaking change 🙂

**Comment by adam-fowler** [comment]
To use the multipart extension code you would need to import SotoS3Extension.

**Comment by MahdiBM** [comment]
So ... a @_exported wouldn't salvage the situation?

**Comment by adam-fowler** [comment]
That'd produce a weird dynamic where SotoS3Extension is dependent on SotoS3 but is imported into SotoS3Extension, so SotoS3 becomes dependent on SotoS3Extension. Not sure that is possible. 

I guess you could have a SotoS3Service target that holds the generated code, SotoS3Extension that holds the extension code and then SotoS3 that imports both with `@_exported`. That might work but it's bloody horrible.

**Comment by MahdiBM** [comment]
Honestly I don't see how that's horrible 😅
Makes a fine sense to me, specially to avoid a new major version.

I do see the difference but generally speaking, "umbrella modules" aren't rare. NIO for example.

Not that I'll be bothered with a new major version, but it feels awkward to have a new major version just for this, so I thought I take my shot to see if we can avoid that.

It's fine either way, for me.

**Pull request closed without merging**
